/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as InspectRouteImport } from './routes/inspect'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as ApiAnalyticsRouteImport } from './routes/api/analytics'
import { Route as ApiHistoryRouteImport } from './routes/api/history'
import { Route as ApiInspectRouteImport } from './routes/api/inspect'
import { Route as ApiMachineStatusRouteImport } from './routes/api/machine-status'
import { Route as ApiRiskRouteImport } from './routes/api/risk'
import { Route as ApiSimulateRouteImport } from './routes/api/simulate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectRoute = InspectRouteImport.update({
  id: '/inspect',
  path: '/inspect',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsRoute = ApiAnalyticsRouteImport.update({
  id: '/api/analytics',
  path: '/api/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInspectRoute = ApiInspectRouteImport.update({
  id: '/api/inspect',
  path: '/api/inspect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMachineStatusRoute = ApiMachineStatusRouteImport.update({
  id: '/api/machine-status',
  path: '/api/machine-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRiskRoute = ApiRiskRouteImport.update({
  id: '/api/risk',
  path: '/api/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSimulateRoute = ApiSimulateRouteImport.update({
  id: '/api/simulate',
  path: '/api/simulate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/history': typeof HistoryRoute
  '/inspect': typeof InspectRoute
  '/monitoring': typeof MonitoringRoute
  '/risk': typeof RiskRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/inspect': typeof ApiInspectRoute
  '/api/machine-status': typeof ApiMachineStatusRoute
  '/api/risk': typeof ApiRiskRoute
  '/api/simulate': typeof ApiSimulateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/history': typeof HistoryRoute
  '/inspect': typeof InspectRoute
  '/monitoring': typeof MonitoringRoute
  '/risk': typeof RiskRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/inspect': typeof ApiInspectRoute
  '/api/machine-status': typeof ApiMachineStatusRoute
  '/api/risk': typeof ApiRiskRoute
  '/api/simulate': typeof ApiSimulateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/history': typeof HistoryRoute
  '/inspect': typeof InspectRoute
  '/monitoring': typeof MonitoringRoute
  '/risk': typeof RiskRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/inspect': typeof ApiInspectRoute
  '/api/machine-status': typeof ApiMachineStatusRoute
  '/api/risk': typeof ApiRiskRoute
  '/api/simulate': typeof ApiSimulateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/history'
    | '/inspect'
    | '/monitoring'
    | '/risk'
    | '/settings'
    | '/simulator'
    | '/api/analytics'
    | '/api/history'
    | '/api/inspect'
    | '/api/machine-status'
    | '/api/risk'
    | '/api/simulate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/history'
    | '/inspect'
    | '/monitoring'
    | '/risk'
    | '/settings'
    | '/simulator'
    | '/api/analytics'
    | '/api/history'
    | '/api/inspect'
    | '/api/machine-status'
    | '/api/risk'
    | '/api/simulate'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/history'
    | '/inspect'
    | '/monitoring'
    | '/risk'
    | '/settings'
    | '/simulator'
    | '/api/analytics'
    | '/api/history'
    | '/api/inspect'
    | '/api/machine-status'
    | '/api/risk'
    | '/api/simulate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  HistoryRoute: typeof HistoryRoute
  InspectRoute: typeof InspectRoute
  MonitoringRoute: typeof MonitoringRoute
  RiskRoute: typeof RiskRoute
  SettingsRoute: typeof SettingsRoute
  SimulatorRoute: typeof SimulatorRoute
  ApiAnalyticsRoute: typeof ApiAnalyticsRoute
  ApiHistoryRoute: typeof ApiHistoryRoute
  ApiInspectRoute: typeof ApiInspectRoute
  ApiMachineStatusRoute: typeof ApiMachineStatusRoute
  ApiRiskRoute: typeof ApiRiskRoute
  ApiSimulateRoute: typeof ApiSimulateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspect': {
      id: '/inspect'
      path: '/inspect'
      fullPath: '/inspect'
      preLoaderRoute: typeof InspectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics': {
      id: '/api/analytics'
      path: '/api/analytics'
      fullPath: '/api/analytics'
      preLoaderRoute: typeof ApiAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inspect': {
      id: '/api/inspect'
      path: '/api/inspect'
      fullPath: '/api/inspect'
      preLoaderRoute: typeof ApiInspectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/machine-status': {
      id: '/api/machine-status'
      path: '/api/machine-status'
      fullPath: '/api/machine-status'
      preLoaderRoute: typeof ApiMachineStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/risk': {
      id: '/api/risk'
      path: '/api/risk'
      fullPath: '/api/risk'
      preLoaderRoute: typeof ApiRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/simulate': {
      id: '/api/simulate'
      path: '/api/simulate'
      fullPath: '/api/simulate'
      preLoaderRoute: typeof ApiSimulateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  HistoryRoute: HistoryRoute,
  InspectRoute: InspectRoute,
  MonitoringRoute: MonitoringRoute,
  RiskRoute: RiskRoute,
  SettingsRoute: SettingsRoute,
  SimulatorRoute: SimulatorRoute,
  ApiAnalyticsRoute: ApiAnalyticsRoute,
  ApiHistoryRoute: ApiHistoryRoute,
  ApiInspectRoute: ApiInspectRoute,
  ApiMachineStatusRoute: ApiMachineStatusRoute,
  ApiRiskRoute: ApiRiskRoute,
  ApiSimulateRoute: ApiSimulateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
